name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: Prepare
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        echo ${TAG}
         
  
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag samimbsnl/githubaction:V1.0
      
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: samimbsnl/githubaction:V1.0
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/githubaction:V1.0
      
    - name: Docker logout
      run: docker logout

